GET http://localhost:3011/users

###

POST http://localhost:3010/posts
Authorization: Bearer 

### 

POST http://localhost:3011/users
Content-Type: application/json

{
  "username": "aap",
  "password": "apekop"
}

###

POST http://localhost:3011/login
Content-Type: application/json

{
  "username": "gijs",
  "password": "apekop"
}

###

POST http://localhost:3011/token
Content-Type: application/json

{
  "token": ""
}

###

DELETE http://localhost:3011/logout
Content-Type: application/json

{
  "token": ""
}
