GET http://localhost:3011/users

###

POST http://localhost:3010/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpanMiLCJwYXNzd29yZCI6IiQyYiQxMCRkdk9FZE94OHEwV1ouSHdFQXdmNWkudGZIQ08vbzRvVFFuOFRxN3pXbTl0dlJGZERlYXh0cSIsImlhdCI6MTYyNzMyNzE3Nn0.3T1x6fG7V9k3l1P1jc6ofgIguzpCWJh_EhiFsnB9uRo

### 

POST http://localhost:3011/users
Content-Type: application/json

{
  "username": "aap",
  "password": "apekop"
}

###

POST http://localhost:3011/login
Content-Type: application/json

{
  "username": "gijs",
  "password": "apekop"
}
